spring:
  application:
    name: ingest-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8081

pulse:
  stream:
    key: metrics
    group: pulse-ingest
    consumer: ingest-1
